displayName=Activity Counter
author=Maximuis94
description=Plugin that counts activities (e.g. bosses/agility laps) per manually defined session
tags=session,tracker,counter,kc,killcount,activity,lap
plugins=com.activitycounter.ActivityCounterPlugin
build=standard