displayName=Dynamic line of sight
author=Maximuis94
description=Adds customizable player Lines of Sight. Uses current weapon and Myopia tier. Adds NPC LoS for Colosseum, Inferno and Fight Caves.
tags=combat,weapon,attack,range,line,sight,los,myopia,fortis,colosseum,safespot,safe,spot,npc,fight,caves,inferno
plugins=com.dynamiclos.DynamicLineOfSightPlugin
build=standard
