package com.datalogger.ui.modes;

import static com.datalogger.constants.PluginConstants.INTERNAL_VAULT_DIR;
import com.datalogger.constants.PluginConstants;
import com.datalogger.models.enums.UIScrollSpeed;
import com.datalogger.models.itemvault.BankedItem;
import com.datalogger.services.AccountHashMapper;
import com.datalogger.ui.utils.Components;
import com.datalogger.ui.utils.Models.VaultItem;
import com.datalogger.ui.utils.Models.AccountItem;
import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.io.File;
import java.io.FileReader;
import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.concurrent.ScheduledExecutorService;
import javax.inject.Inject;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollBar;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.SwingUtilities;
import javax.swing.ToolTipManager;
import javax.swing.border.EmptyBorder;
import javax.swing.event.PopupMenuEvent;
import javax.swing.event.PopupMenuListener;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import lombok.extern.slf4j.Slf4j;
import net.runelite.api.ItemComposition;
import net.runelite.client.callback.ClientThread;
import net.runelite.client.game.ItemManager;
import net.runelite.client.ui.ColorScheme;
import net.runelite.client.util.AsyncBufferedImage;

@Slf4j
public class ItemsManagerModePanel extends JPanel
{
	private String accountName = null;
	private long accountHash = -1L;

	private final JComboBox<AccountItem> accountSelector;
	private final JComboBox<VaultItem> vaultSelector;

	private final JPanel contentPanel;

	private final AccountHashMapper accountHashMapper;
	private final Gson gson;
	private final ScheduledExecutorService executor;
	private final ItemManager itemManager;

	private final ClientThread clientThread;

	private UIScrollSpeed scrollSpeed = UIScrollSpeed.MEDIUM;
	private JScrollBar scrollBar = null;

	@Inject
	public ItemsManagerModePanel(AccountHashMapper accountHashMapper, Gson gson, ScheduledExecutorService executor, ItemManager itemManager, ClientThread clientThread)
	{
		this.accountHashMapper = accountHashMapper;
		this.gson = gson;
		this.executor = executor;
		this.itemManager = itemManager;
		this.clientThread = clientThread;

		setLayout(new BorderLayout(0, 10));
		setBackground(ColorScheme.DARK_GRAY_COLOR);
		setBorder(new EmptyBorder(10, 10, 10, 10));

		contentPanel = new JPanel(new BorderLayout());
		contentPanel.setBackground(ColorScheme.DARK_GRAY_COLOR);
		add(contentPanel, BorderLayout.CENTER);

		JPanel northWrapper = new JPanel(new BorderLayout(0, 10));
		northWrapper.setBackground(ColorScheme.DARK_GRAY_COLOR);

		JPanel targetPanel = Components.createTitledPanel("Specify data", new GridLayout(0, 1, 0, 5));

		accountSelector = Components.createComboBox();
		accountSelector.addPopupMenuListener(new PopupMenuListener() {
			@Override public void popupMenuWillBecomeVisible(PopupMenuEvent e) { populateAccounts(); }
			@Override public void popupMenuWillBecomeInvisible(PopupMenuEvent e) {}
			@Override public void popupMenuCanceled(PopupMenuEvent e) {}
		});

		vaultSelector = Components.createComboBox();
		vaultSelector.setEnabled(false);

		targetPanel.add(accountSelector);
		targetPanel.add(vaultSelector);

		JPanel deletePanel = Components.createTitledPanel("Delete internal plugin data", new GridLayout(0, 1, 0, 5));

		JButton resetAccountBtn = Components.createStyledButton("Delete Account Data", e -> {
			if (accountHash == -1L) return;

			ToolTipManager.sharedInstance().setEnabled(false);
			ToolTipManager.sharedInstance().setEnabled(true);

			int confirm = JOptionPane.showConfirmDialog(
				SwingUtilities.getWindowAncestor(this), // Fix for centering in application
				"Are you sure? This will delete all internal item data generated by this plugin for account " + accountName,
				"Confirm Delete All",
				JOptionPane.YES_NO_OPTION,
				JOptionPane.WARNING_MESSAGE
			);

			if (confirm == JOptionPane.YES_OPTION) {
				File accountVaultDir = new File(PluginConstants.INTERNAL_VAULT_DIR, String.valueOf(accountHash));
				if (accountVaultDir.exists() && accountVaultDir.isDirectory()) {
					File[] files = accountVaultDir.listFiles();
					if (files != null) {
						for (File file : files) {
							if (file.getName().endsWith(".json")) file.delete();
						}
					}
				}

				populateVaultsForAccount(accountHash);
				contentPanel.removeAll();
				contentPanel.revalidate();
				contentPanel.repaint();
			}
		});
		resetAccountBtn.setEnabled(false);
		resetAccountBtn.setForeground(ColorScheme.PROGRESS_ERROR_COLOR);
		resetAccountBtn.setToolTipText("Delete ALL item data for the selected account");

		JButton resetVaultBtn = Components.createStyledButton("Delete Vault Data", e -> {
			Object selected = vaultSelector.getSelectedItem();
			if (selected instanceof VaultItem) {
				VaultItem vaultItem = (VaultItem) selected;

				ToolTipManager.sharedInstance().setEnabled(false);
				ToolTipManager.sharedInstance().setEnabled(true);

				int confirm = JOptionPane.showConfirmDialog(
					SwingUtilities.getWindowAncestor(this), // Fix for centering in application
					"Are you sure you want to delete the vault: " + vaultItem.getDisplayName() + "?\nThis action cannot be undone.",
					"Confirm Delete",
					JOptionPane.YES_NO_OPTION,
					JOptionPane.WARNING_MESSAGE
				);

				if (confirm == JOptionPane.YES_OPTION) {
					File vaultFile = new File(PluginConstants.INTERNAL_VAULT_DIR, accountHash + File.separator + vaultItem.getActualFileName());
					if (vaultFile.exists()) vaultFile.delete();

					populateVaultsForAccount(accountHash);
					contentPanel.removeAll();
					contentPanel.revalidate();
					contentPanel.repaint();
				}
			}
		});
		resetVaultBtn.setEnabled(false);
		resetVaultBtn.setForeground(ColorScheme.PROGRESS_ERROR_COLOR);
		resetVaultBtn.setToolTipText("Delete data from the selected source for the selected account");

		deletePanel.add(resetAccountBtn);
		deletePanel.add(resetVaultBtn);

		northWrapper.add(targetPanel, BorderLayout.NORTH);
		northWrapper.add(deletePanel, BorderLayout.CENTER);
		add(northWrapper, BorderLayout.NORTH);

		vaultSelector.addActionListener(e -> {
			Object selected = vaultSelector.getSelectedItem();
			if (selected instanceof VaultItem) {
				VaultItem selectedVault = (VaultItem) selected;

				resetVaultBtn.setEnabled(true);
				resetVaultBtn.setText("Delete " + selectedVault.getDisplayName() + " data");

				loadVaultItemsFromDisk(selectedVault.getActualFileName());
			} else {
				resetVaultBtn.setEnabled(false);
				resetVaultBtn.setText("Delete vault Data");

				contentPanel.removeAll();
				contentPanel.revalidate();
				contentPanel.repaint();
			}
		});

		accountSelector.addActionListener(e -> {
			AccountItem selected = (AccountItem) accountSelector.getSelectedItem();
			if (selected != null && selected.getHash() != -1L) {
				this.accountName = selected.getName();
				this.accountHash = selected.getHash();

				resetAccountBtn.setEnabled(true);
				resetAccountBtn.setText("Delete account plugin data");

				populateVaultsForAccount(this.accountHash);
			} else {
				this.accountName = null;
				this.accountHash = -1L;

				resetAccountBtn.setEnabled(false);
				resetAccountBtn.setText("Delete account plugin data");

				vaultSelector.removeAllItems();
				vaultSelector.setEnabled(false);

				resetVaultBtn.setEnabled(false);
				resetVaultBtn.setText("Delete vault data");
			}
		});

		populateAccounts();
	}

	private void populateAccounts()
	{
		AccountItem currentSelection = (AccountItem) accountSelector.getSelectedItem();
		long currentSelectedHash = currentSelection != null ? currentSelection.getHash() : -1L;

		accountSelector.removeAllItems();
		accountSelector.addItem(new AccountItem("Select account", -1L));

		List<Long> knownHashes = accountHashMapper.getAccountHashes();

		AccountItem itemToRestore = null;

		for (Long hash : knownHashes) {
			String name = accountHashMapper.getAccountName(hash);
			AccountItem item = new AccountItem(name, hash);
			accountSelector.addItem(item);

			if (hash == currentSelectedHash) {
				itemToRestore = item;
			}
		}

		if (itemToRestore != null) {
			accountSelector.setSelectedItem(itemToRestore);
		}
	}

	private void populateVaultsForAccount(long accountHash)
	{
		vaultSelector.removeAllItems();
		vaultSelector.setEnabled(true);

		File accountVaultDir = new File(INTERNAL_VAULT_DIR, String.valueOf(accountHash));

		if (accountVaultDir.exists() && accountVaultDir.isDirectory())
		{
			File[] vaultFiles = accountVaultDir.listFiles((dir, name) -> name.endsWith(".json"));

			if (vaultFiles != null)
			{
				for (File file : vaultFiles)
				{
					String actualFileName = file.getName();
					String displayName = actualFileName;

					int dotIndex = displayName.lastIndexOf('_');
					if (dotIndex > 0) {
						displayName = displayName.substring(0, dotIndex);
					}

					vaultSelector.addItem(new VaultItem(displayName, actualFileName));
				}
			}
		}

		if (vaultSelector.getItemCount() == 0)
		{
			vaultSelector.setEnabled(false);
		}
	}

	private void loadVaultItemsFromDisk(String vaultFileName)
	{
		contentPanel.removeAll();
		JLabel loadingLabel = new JLabel("Loading items...", SwingConstants.CENTER);
		loadingLabel.setForeground(Color.GRAY);
		contentPanel.add(loadingLabel, BorderLayout.CENTER);
		contentPanel.revalidate();
		contentPanel.repaint();

		executor.submit(() -> {
			List<BankedItem> items = new ArrayList<>();
			File vaultFile = new File(PluginConstants.INTERNAL_VAULT_DIR, accountHash + File.separator + vaultFileName);
			if (vaultFile.exists()) {
				try (FileReader reader = new FileReader(vaultFile)) {
					Type listType = new TypeToken<ArrayList<BankedItem>>(){}.getType();
					List<BankedItem> parsedItems = gson.fromJson(reader, listType);
					if (parsedItems != null) items.addAll(parsedItems);
				} catch (Exception ex) {
					log.warn("Failed to parse vaultFile at '{}'", vaultFile.getAbsolutePath(), ex);
				}
			}

			clientThread.invokeLater(() -> {
				Map<Integer, String> itemNamesMap = new HashMap<>();

				for (BankedItem item : items) {
					try {
						ItemComposition comp = itemManager.getItemComposition(item.getItemId());
						itemNamesMap.put(item.getItemId(), comp.getName());
					} catch (Exception ignored) {}
				}

				SwingUtilities.invokeLater(() -> buildItemsTable(items, itemNamesMap));
			});
		});
	}

	private void buildItemsTable(List<BankedItem> items, Map<Integer, String> itemNamesMap)
	{
		contentPanel.removeAll();

		if (items.isEmpty()) {
			JLabel emptyLabel = new JLabel("No items found in this vault.", SwingConstants.CENTER);
			emptyLabel.setForeground(Color.GRAY);
			contentPanel.add(emptyLabel, BorderLayout.CENTER);
		} else {
			String[] columnNames = {"", "Name", "Quantity"};
			DefaultTableModel tableModel = new DefaultTableModel(columnNames, 0) {
				@Override public boolean isCellEditable(int row, int col) { return false; }
				@Override public Class<?> getColumnClass(int col) {
					if (col == 0) return BankedItem.class;
					if (col == 2) return Long.class;
					return String.class;
				}
			};

			for (BankedItem item : items) {
				long qty = item.getQuantity();
				String name = itemNamesMap.getOrDefault(item.getItemId(), "Unknown");

				tableModel.addRow(new Object[]{item, name, qty});
			}

			JTable itemsTable = new JTable(tableModel);

			itemsTable.setShowVerticalLines(false);
			itemsTable.setShowHorizontalLines(true);
			itemsTable.setIntercellSpacing(new Dimension(0, 0));
			itemsTable.setRowHeight(45);

			itemsTable.setBackground(ColorScheme.DARK_GRAY_COLOR);
			itemsTable.setForeground(Color.WHITE);
			itemsTable.setGridColor(ColorScheme.DARKER_GRAY_COLOR);
			itemsTable.getTableHeader().setBackground(ColorScheme.DARKER_GRAY_COLOR);
			itemsTable.getTableHeader().setForeground(Color.WHITE);
//			itemsTable.setRowHeight(36);
			itemsTable.setAutoCreateRowSorter(true);

			itemsTable.getColumnModel().getColumn(0).setCellRenderer(new ItemIconCellRenderer());
			itemsTable.getColumnModel().getColumn(0).setPreferredWidth(40);
			itemsTable.getColumnModel().getColumn(0).setMaxWidth(40);

			DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
			centerRenderer.setHorizontalAlignment(SwingConstants.CENTER);
			itemsTable.getColumnModel().getColumn(2).setCellRenderer(centerRenderer);

			itemsTable.setPreferredScrollableViewportSize(new Dimension(itemsTable.getPreferredSize().width, 36 * 8));

			JScrollPane scrollPane = Components.createScrollPane(itemsTable);

			scrollBar = scrollPane.getVerticalScrollBar();
			setScrollSpeed(scrollSpeed);

			contentPanel.add(scrollPane, BorderLayout.CENTER);
		}

		contentPanel.revalidate();
		contentPanel.repaint();
	}

	private ImageIcon getIconForItem(int itemId, long quantity)
	{
		if (itemId <= 0) return null;

		int safeQty = quantity > Integer.MAX_VALUE ? Integer.MAX_VALUE : (int) quantity;

		AsyncBufferedImage image = itemManager.getImage(itemId, safeQty, true);
		if (image == null) return null;

		image.onLoaded(() -> SwingUtilities.invokeLater(() -> {
			if (contentPanel != null) contentPanel.repaint();
		}));

		return new ImageIcon(image);
	}

	/**
	 * Set the scroll speed of the inner scrollbar of this panel to a value that corresponds with the given speed
	 */
	public void setScrollSpeed(UIScrollSpeed scrollSpeed)
	{
		this.scrollSpeed = scrollSpeed;
		if (scrollBar ==  null) return;
		switch (scrollSpeed)
		{
			case LOW:
				scrollBar.setUnitIncrement(8);
				break;
			case MEDIUM:
				scrollBar.setUnitIncrement(16);
				break;
			case HIGH:
				scrollBar.setUnitIncrement(32);
				break;
		}
	}

	public class ItemIconCellRenderer extends DefaultTableCellRenderer
	{
		@Override
		public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column)
		{
			super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
			if (value instanceof BankedItem)
			{
				BankedItem item = (BankedItem) value;
				setText(null);
				setIcon(getIconForItem(item.getItemId(), item.getQuantity()));
				setToolTipText(item.getItemName());
				setHorizontalAlignment(SwingConstants.CENTER);
			}
			return this;
		}
	}
}