/*
 * Copyright (c) 2026, maximuis94 <https://github.com/maximuis94>
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this
 *    list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

package com.datalogger.models.enums;

import java.util.HashMap;
import java.util.Map;
import lombok.Getter;
import net.runelite.api.gameval.ItemID;

/**
 * Enumeration with STASH unit data.
 * Used primarily as a fallback mechanism when inventory diffing fails during a deposit.
 */
@Getter
public enum StashUnitData
{
	NEAR_A_SHED_IN_LUMBRIDGE_SWAMP(28958, false, new int[]{ItemID.BRONZE_DAGGER, ItemID.IRON_FULL_HELM, ItemID.GOLD_RING}),
	ON_THE_BRIDGE_TO_THE_MISTHALIN_WIZARDS_TOWER(28959, false, new int[]{ItemID.IRON_MED_HELM, ItemID.EMERALD_RING, ItemID.WHITE_APRON}),
	DRAYNOR_VILLAGE_MARKET(28960, false, new int[]{ItemID.STUDDED_CHAPS, ItemID.IRON_KITESHIELD, ItemID.STEEL_LONGSWORD}),
	LIMESTONE_MINE(28961, false, new int[]{ItemID.BRONZE_PLATELEGS, ItemID.STEEL_PICKAXE, ItemID.STEEL_MED_HELM}),
	OUTSIDE_THE_LEGENDS_GUILD_GATES(28962, false, new int[]{ItemID.IRON_PLATELEGS, ItemID.OAK_LONGBOW, ItemID.STRUNG_EMERALD_AMULET}),
	MUDSKIPPER_POINT(28963, false, new int[]{ItemID.BLACK_CAPE, ItemID.LEATHER_CHAPS, ItemID.STEEL_MACE}),
	NEAR_THE_ENTRANA_FERRY_IN_PORT_SARIM(28964, false, new int[]{ItemID.COIF, ItemID.STEEL_PLATESKIRT, ItemID.SAPPHIRE_NECKLACE}),
	AL_KHARID_SCORPION_MINE(28965, false, new int[]{ItemID.DESERT_SHIRT, ItemID.LEATHER_GLOVES, ItemID.LEATHER_BOOTS}),
	DRAYNOR_MANOR_BY_THE_FOUNTAIN(28966, false, new int[]{ItemID.IRON_PLATEBODY, ItemID.STUDDED_CHAPS, ItemID.BRONZE_FULL_HELM}),
	WHEAT_FIELD_NEAR_THE_LUMBRIDGE_WINDMILL(28967, false, new int[]{ItemID.GNOME_ROBETOP_BLUE, ItemID.GNOME_ROBEBOTTOMS_TURQUOISE, ItemID.OAK_SHORTBOW}),
	CROSSROADS_NORTH_OF_DRAYNOR_VILLAGE(28968, false, new int[]{ItemID.IRON_CHAINBODY, ItemID.SAPPHIRE_RING, ItemID.LONGBOW}),
	RIMMINGTON_MINE(28969, false, new int[]{ItemID.GOLD_NECKLACE, ItemID.GOLD_RING, ItemID.BRONZE_SPEAR}),
	VARROCK_PALACE_LIBRARY(28970, false, new int[]{ItemID.GNOME_ROBETOP_GREEN, ItemID.HAM_ROBE, ItemID.IRON_WARHAMMER}),
	UPSTAIRS_IN_THE_ARDOUGNE_WINDMILL(28971, false, new int[]{ItemID.GNOME_ROBETOP_BLUE, ItemID.HAM_ROBE, ItemID.TIARA}),
	OUTSIDE_THE_FALADOR_PARTY_ROOM(28972, false, new int[]{ItemID.STEEL_FULL_HELM, ItemID.STEEL_PLATEBODY, ItemID.IRON_PLATESKIRT}),
	TAVERLEY_STONE_CIRCLE(28973, false, new int[]{ItemID.BLUEWIZHAT, ItemID.BRONZE_2H_SWORD, ItemID.HAM_BOOTS}),
	CATHERBY_BEEHIVE_FIELD(28974, false, new int[]{ItemID.DESERT_SHIRT, ItemID.GNOME_ROBEBOTTOMS_GREEN, ItemID.STEEL_AXE}),
	NEAR_THE_PARROTS_IN_ARDOUGNE_ZOO(28975, false, new int[]{ItemID.STUDDED_BODY, ItemID.BRONZE_PLATELEGS, ItemID.PLAINSTAFF}),
	ROAD_JUNCTION_NORTH_OF_RIMMINGTON(28976, false, new int[]{ItemID.GNOME_HAT_GREEN, ItemID.GNOME_ROBETOP_CREAM, ItemID.LEATHER_CHAPS}),
	OUTSIDE_THE_FISHING_GUILD(28977, false, new int[]{ItemID.EMERALD_RING, ItemID.STRUNG_SAPPHIRE_AMULET, ItemID.BRONZE_CHAINBODY}),
	OUTSIDE_KEEP_LE_FAYE(28978, false, new int[]{ItemID.COIF, ItemID.IRON_PLATEBODY, ItemID.LEATHER_GLOVES}),
	ROAD_JUNCTION_SOUTH_OF_SINCLAIR_MANSION(28979, false, new int[]{ItemID.LEATHER_COWL, ItemID.WIZARDS_ROBE, ItemID.IRON_SCIMITAR}),
	OUTSIDE_THE_DIGSITE_EXAM_CENTRE(28980, false, new int[]{ItemID.WHITE_APRON, ItemID.GNOME_BOOTS_GREEN, ItemID.LEATHER_GLOVES}),
	NEAR_THE_SAWMILL_OPERATORS_BOOTH(28981, false, new int[]{ItemID.HARDLEATHER_BODY, ItemID.LEATHER_CHAPS, ItemID.BRONZE_AXE}),
	EMIRS_ARENA_TICKET_OFFICE(28982, false, new int[]{ItemID.IRON_CHAINBODY, ItemID.LEATHER_CHAPS, ItemID.COIF}),
	OUTSIDE_VARROCK_PALACE_COURTYARD(28983, false, new int[]{ItemID.BLACK_AXE, ItemID.COIF, ItemID.RUBY_RING}),
	NEAR_HERQUINS_SHOP_IN_FALADOR(28984, false, new int[]{ItemID.MITHRIL_PICKAXE, ItemID.BLACK_PLATEBODY, ItemID.IRON_KITESHIELD}),
	SOUTH_OF_THE_GRAND_EXCHANGE(28985, false, new int[]{ItemID.PINK_SKIRT, ItemID.GNOME_ROBETOP_PINK, ItemID.TIARA_BODY}),
	AUBURYS_SHOP_IN_VARROCK(28986, false, new int[]{ItemID.TIARA_AIR, ItemID.STAFF_OF_WATER}),
	CENTRE_OF_CANIFIS(28987, false, new int[]{ItemID.GNOME_ROBETOP_GREEN, ItemID.MITHRIL_PLATELEGS, ItemID.IRON_2H_SWORD}),
	MAUSOLEUM_OFF_THE_MORYTANIA_COAST(28988, false, new int[]{ItemID.MITHRIL_PLATESKIRT, ItemID.MAPLE_LONGBOW}),
	EAST_OF_THE_BARBARIAN_VILLAGE_BRIDGE(28989, false, new int[]{ItemID.WOLFENGLOVES_PURPLE, ItemID.STEEL_KITESHIELD, ItemID.MITHRIL_FULL_HELM}),
	SOUTH_OF_THE_SHRINE_IN_TAI_BWO_WANNAI_VILLAGE(28990, true, new int[]{ItemID.DRAGONHIDE_CHAPS, ItemID.RING_OF_DUELING_1, ItemID.MITHRIL_MED_HELM}), // Dueling rings have charges
	CASTLE_WARS_BANK(28991, true, new int[]{ItemID.STRUNG_RUBY_AMULET, ItemID.MITHRIL_SCIMITAR, ItemID.WILDERNESS_CAPE_1}), // Any team cape
	BARBARIAN_OUTPOST_OBSTACLE_COURSE(28992, true, new int[]{ItemID.STEEL_PLATEBODY, ItemID.MAPLE_SHORTBOW, ItemID.WILDERNESS_CAPE_1}), // Any team cape
	GNOME_STRONGHOLD_BALANCING_ROPE(28993, true, new int[]{ItemID.STEEL_KITESHIELD, ItemID.RING_OF_FORGING, ItemID.DRAGONHIDE_CHAPS}), // Forging rings have charges
	OUTSIDE_YANILLE_BANK(28994, false, new int[]{ItemID.BROWN_APRON, ItemID.ADAMANT_MED_HELM, ItemID.SNAKESKIN_CHAPS}),
	OBSERVATORY(28995, false, new int[]{ItemID.MITHRIL_CHAINBODY, ItemID.DRAGONHIDE_CHAPS, ItemID.STRUNG_RUBY_AMULET}),
	OGRE_CAGE_IN_KING_LATHAS_TRAINING_CAMP(28996, false, new int[]{ItemID.DRAGONHIDE_BODY, ItemID.DRAGONHIDE_CHAPS, ItemID.STEEL_SQ_SHIELD}),
	DIGSITE(28997, false, new int[]{ItemID.GNOME_HAT_GREEN, ItemID.SNAKESKIN_BOOTS, ItemID.IRON_PICKAXE}),
	HICKTONS_ARCHERY_EMPORIUM(28998, false, new int[]{ItemID.GNOME_BOOTS_BLUE, ItemID.HARDLEATHER_BODY, ItemID.SILVER_SICKLE}),
	SHANTAY_PASS(28999, false, new int[]{ItemID.SNELM_POINT_BLUE, ItemID.STAFF_OF_AIR, ItemID.BRONZE_SQ_SHIELD}),
	LUMBRIDGE_SWAMP_CAVES(29000, false, new int[]{ItemID.STAFF_OF_AIR, ItemID.BRONZE_FULL_HELM, ItemID.AMULET_OF_POWER}),
	OUTSIDE_CATHERBY_BANK(29001, false, new int[]{ItemID.MAPLE_LONGBOW, ItemID.DRAGONHIDE_CHAPS, ItemID.IRON_MED_HELM}),
	OUTSIDE_THE_SEERS_VILLAGE_COURTHOUSE(29002, false, new int[]{ItemID.ADAMANT_HALBERD, ItemID.MYSTIC_ROBE_BOTTOM, ItemID.DIAMOND_RING}),
	OUTSIDE_HARRYS_FISHING_SHOP_IN_CATHERBY(29003, false, new int[]{ItemID.ADAMANT_SQ_SHIELD, ItemID.DTTD_BONE_DAGGER, ItemID.MITHRIL_PLATEBODY}),
	TZHAAR_WEAPONS_STORE(29004, false, new int[]{ItemID.STEEL_LONGSWORD, ItemID.BLUE_DRAGONHIDE_BODY, ItemID.MYSTIC_GLOVES}),
	NORTH_OF_EVIL_DAVES_HOUSE_IN_EDGEVILLE(29005, false, new int[]{ItemID.BROWN_APRON, ItemID.LEATHER_BOOTS, ItemID.LEATHER_GLOVES}),
	WEST_OF_THE_SHAYZIEN_COMBAT_RING(29006, false, new int[]{ItemID.ADAMANT_PLATELEGS, ItemID.ADAMANT_PLATEBODY, ItemID.ADAMANT_FULL_HELM}),
	ENTRANCE_OF_THE_ARCEUUS_LIBRARY(29007, false, new int[]{ItemID.BLUE_DRAGON_VAMBRACES, ItemID.ADAMANT_ARMOURED_BOOTS, ItemID.ADAMANT_DAGGER}),
	OUTSIDE_DRAYNOR_VILLAGE_JAIL(29008, false, new int[]{ItemID.ADAMANT_SWORD, ItemID.STRUNG_SAPPHIRE_AMULET, ItemID.ADAMANT_PLATESKIRT}),
	EAST_OF_THE_LEVEL_19_WILDERNESS_OBELISK(29009, false, new int[]{ItemID.RUNE_PLATELEGS, ItemID.IRON_PLATEBODY, ItemID.BLUE_DRAGON_VAMBRACES}),
	FISHING_GUILD_BANK(29010, false, new int[]{ItemID.ELEMENTAL_SHIELD, ItemID.BLUE_DRAGONHIDE_CHAPS, ItemID.RUNE_WARHAMMER}),
	TOP_FLOOR_OF_THE_LIGHTHOUSE(29011, false, new int[]{ItemID.BLUE_DRAGONHIDE_BODY, ItemID.BLUE_DRAGON_VAMBRACES}),
	OUTSIDE_THE_GREAT_PYRAMID_OF_SOPHANEM(29012, false, new int[]{ItemID.RING_OF_LIFE, ItemID.AMULET_OF_GLORY, ItemID.ADAMANT_2H_SWORD}),
	NOTERAZZOS_SHOP_IN_THE_WILDERNESS(29013, false, new int[]{ItemID.ADAMANT_SQ_SHIELD, ItemID.BLUE_DRAGON_VAMBRACES, ItemID.RUNE_PICKAXE}),
	WEST_SIDE_OF_THE_KARAMJA_BANANA_PLANTATION(29014, false, new int[]{ItemID.DIAMOND_RING, ItemID.AMULET_OF_POWER}),
	MOUNTAIN_CAMP_GOAT_ENCLOSURE(29015, false, new int[]{ItemID.RUNE_FULL_HELM, ItemID.BLUE_DRAGONHIDE_CHAPS, ItemID.FIRE_BATTLESTAFF}),
	GNOME_GLIDER_ON_WHITE_WOLF_MOUNTAIN(29016, false, new int[]{ItemID.MITHRIL_PLATELEGS, ItemID.RING_OF_LIFE, ItemID.RUNE_AXE}),
	SHILO_VILLAGE_BANK(29017, false, new int[]{ItemID.MYSTIC_HAT, ItemID.CAVE_GOBLIN_BONE_SPEAR, ItemID.RUNE_PLATEBODY}),
	INSIDE_THE_DIGSITE_EXAM_CENTRE(29018, false, new int[]{ItemID.MYSTIC_FIRE_STAFF, ItemID.JEWL_DIAMOND_BRACELET, ItemID.RUNE_ARMOURED_BOOTS}),
	NORTHEAST_CORNER_OF_THE_KHARAZI_JUNGLE(29019, true, new int[]{ItemID.TRAIL_GUTHIX_SCARF, ItemID.RUNE_HERALDIC_KITESHIELD1}), // Stole & Heraldic variants
	VOLCANO_IN_THE_NORTHEASTERN_WILDERNESS(29020, true, new int[]{ItemID.HEADBAND_RED, ItemID.TRAIL_ANCIENT_STAFF}), // Headband & Crozier variants
	IN_THE_MIDDLE_OF_JIGGIG(29021, true, new int[]{ItemID.TRAIL_HERALDIC_HELM_1_RUNE, ItemID.RUNE_SPEAR, ItemID.RUNE_PLATELEGS}), // Heraldic helm
	AGILITY_PYRAMID(29022, true, new int[]{ItemID.MYSTIC_ROBE_TOP, ItemID.RUNE_HERALDIC_KITESHIELD1}), // Heraldic shield
	HOSIDIUS_MESS(29023, false, new int[]{ItemID.RUNE_HALBERD, ItemID.RUNE_PLATEBODY, ItemID.AMULET_OF_STRENGTH}),
	CHAPEL_IN_WEST_ARDOUGNE(29024, false, new int[]{ItemID.DRAGON_SPEAR, ItemID.RED_DRAGONHIDE_CHAPS}),
	NEAR_A_RUNITE_ROCK_IN_THE_FREMENNIK_ISLES(29025, false, new int[]{ItemID.RUNE_ARMOURED_BOOTS, ItemID.BASIC_TK_RANK2_BODY, ItemID.DRAGONSTONE_RING}),
	NEAR_A_LADDER_IN_THE_WILDERNESS_LAVA_MAZE(29026, true, new int[]{ItemID.BLACK_DRAGONHIDE_CHAPS, ItemID.HUNTING_LIGHT_CAPE, ItemID.HUNDRED_ROLLINGPIN}), // Any spotted cape
	ENTRANCE_OF_THE_CAVE_OF_DAMIS(29027, true, new int[]{ItemID.TRAIL_GUTHIX_MITRE, ItemID.XBOWS_CROSSBOW_RUNITE, ItemID.DEATH_CLIMBINGBOOTS, ItemID.RING_OF_SHADOWS}), // Mitres & Shadow rings
	WARRIORS_GUILD_BANK(29028, false, new int[]{ItemID.BLACK_SALAMANDER}),
	SOUTHEAST_CORNER_OF_THE_MONASTERY(29029, true, new int[]{ItemID.SARADOMINBOOK_COMPLETE}), // Any god book
	SOUTHEAST_CORNER_OF_THE_FISHING_PLATFORM(29030, true, new int[]{ItemID.AMULET_OF_GLORY, ItemID.HUNDRED_GAUNTLETS_LEVEL_10, ItemID.DRAGON_MED_HELM}), // Glory charges
	OUTSIDE_THE_SLAYER_TOWER_GARGOYLE_ROOM(29031, true, new int[]{ItemID.DAGANOTH_CAVE_MAGIC_SHORTBOW, ItemID.JEWL_BRACELET_OF_COMBAT_4, ItemID.FRIS_KINGLY_HELM}), // Combat bracelet charges
	ON_TOP_OF_TROLLHEIM_MOUNTAIN(29032, true, new int[]{ItemID.LAVA_BATTLESTAFF, ItemID.BLACK_DRAGON_VAMBRACES, ItemID.ELEMENTAL_MIND_SHIELD}), // Lava staff variants
	FOUNTAIN_OF_HEROES(29033, true, new int[]{ItemID.SPLITBARK_LEGS, ItemID.DRAGON_BOOTS, ItemID.RUNE_LONGSWORD}), // Dragon/Primordial boots
	ENTRANCE_OF_THE_CAVERN_UNDER_THE_WHIRLPOOL(29034, true, new int[]{ItemID.GRANITE_SHIELD, ItemID.SPLITBARK_BODY, ItemID.TRAIL_HERALDIC_HELM_1_RUNE}), // Heraldic helm
	HALFWAY_DOWN_TROLLWEISS_MOUNTAIN(29035, false, new int[]{ItemID.BLUE_DRAGON_VAMBRACES, ItemID.DRAGON_SPEAR, ItemID.RUNE_PLATESKIRT, ItemID.TROLLROMANCE_TOBOGGON_WAXED}),
	SHAYZIEN_WAR_TENT(29036, true, new int[]{ItemID.MYSTIC_ROBE_BOTTOM, ItemID.RUNE_KITESHIELD, ItemID.TRAIL_BOB_SHIRT_RED}), // Any bob shirt
	OUTSIDE_THE_LEGENDS_GUILD_DOOR(29037, true, new int[]{ItemID.CAPE_OF_LEGENDS, ItemID.DRAGON_BATTLEAXE, ItemID.AMULET_OF_GLORY}), // Glory charges, d-battleaxe variants
	NEAR_THE_GEM_STALL_IN_ARDOUGNE_MARKET(29038, true, new int[]{ItemID.JEWL_CASTLEWARS_BRACELET3, ItemID.STRUNG_DRAGONSTONE_AMULET, ItemID.RING_OF_FORGING}), // Castle wars bracelet tiers
	OUTSIDE_THE_BAR_BY_THE_FIGHT_ARENA(29039, true, new int[]{ItemID.PIRATE_BANDANNA, ItemID.DRAGONSTONE_NECKLACE, ItemID.MAGIC_LONGBOW}), // Pirate bandana colors
	SOUTHEAST_CORNER_OF_LAVA_DRAGON_ISLE(29040, false, new int[]{ItemID.DRAGON_MED_HELM, ItemID.TZHAAR_SPIKESHIELD, ItemID.OLAF2_BRINE_SABRE, ItemID.RUNE_PLATEBODY, ItemID.AMULET_OF_GLORY}), // Clue requires strictly Uncharged glory
	NEAR_THE_PIER_IN_ZULANDRA(29041, true, new int[]{ItemID.DRAGON_2H_SWORD, ItemID.BANDOS_BOOTS, ItemID.TZHAAR_CAPE_OBSIDIAN}), // Bandos/Guardian/Echo boots
	BARROWS_CHEST(29042, true, new int[]{ItemID.BARROWS_DHAROK_HEAD, ItemID.BARROWS_DHAROK_WEAPON, ItemID.BARROWS_DHAROK_BODY, ItemID.BARROWS_DHAROK_LEGS}), // Any Barrows Set
	WELL_OF_VOYAGE(29043, true, new int[]{ItemID.IBANSTAFF, ItemID.MYSTIC_ROBE_TOP_DARK, ItemID.MYSTIC_ROBE_BOTTOM_DARK}), // Iban staff upgrades
	NORTHERN_WALL_OF_CASTLE_DRAKAN(29044, true, new int[]{ItemID.DRAGON_SQ_SHIELD, ItemID.SPLITBARK_BODY, ItemID.STRAWBOATER_RED}), // Boater colors
	_7TH_CHAMBER_OF_JALSAVRAH(29045, true, new int[]{ItemID.NTK_JEWELLED_SCEPTRE_3, ItemID.ROGUETRADER_MENAPHITE_HAT, ItemID.ROGUETRADER_MENAPHITE_TOP, ItemID.ROGUETRADER_MENAPHITE_LEGS}), // Sceptre charges & Menaphite variants
	SOUL_ALTAR(29046, true, new int[]{ItemID.DRAGON_PICKAXE, ItemID.FRIS_KINGLY_HELM, ItemID.RUNE_ARMOURED_BOOTS}), // Pickaxe variants (Dragon, Crystal, Infernal)
	WARRIORS_GUILD_BANK_29047(29047, true, new int[]{ItemID.DRAGON_BATTLEAXE, ItemID.DRAGON_PARRYINGDAGGER, ItemID.SLAYER_HELM}), // Any slayer helm, avernic/dragon def
	ENTRANA_CHAPEL(29048, false, new int[]{ItemID.BLACK_DRAGON_VAMBRACES, ItemID.BLACK_DRAGONHIDE_CHAPS, ItemID.BLACK_DRAGONHIDE_BODY}),
	TZHAAR_GEM_STORE(29049, true, new int[]{ItemID.TZHAAR_CAPE_FIRE, ItemID.TZHAAR_THROWINGRING}), // Fire, Infernal, Max capes
	TENT_IN_LORD_IORWERTHS_ENCAMPMENT(29050, true, new int[]{ItemID.CRYSTAL_BOW}), // Crystal Bow / Bow of Faerdhinen
	OUTSIDE_MUDKNUCKLES_HUT(29051, true, new int[]{ItemID.RUNE_PLATEBODY_BANDOS, ItemID.TRAIL_BANDOS_CLOAK, ItemID.BGS}), // BGS variants
	CENTRE_OF_THE_CATACOMBS_OF_KOUREND(29052, true, new int[]{ItemID.ARCLIGHT, ItemID.DAMNED_AMULET}), // Arclight/Emberlight, Damned amulets
	KING_BLACK_DRAGONS_LAIR(29053, false, new int[]{ItemID.BLACK_DRAGONHIDE_BODY, ItemID.BLACK_DRAGON_VAMBRACES, ItemID.DRAGONMASK_BLACK}),
	OUTSIDE_KRIL_TSUTSAROTHS_ROOM(29054, false, new int[]{ItemID.RUNE_FULL_HELM_ZAMORAK, ItemID.SHADOW_MAJ_SHADOW_SWORD}),
	BY_THE_BEAR_CAGE_IN_VARROCK_PALACE_GARDENS(29055, true, new int[]{ItemID.ZGS}), // ZGS variants
	OUTSIDE_THE_WILDERNESS_AXE_HUT(29056, false, new int[]{ItemID.TRAIL_FLARED_PANTS, ItemID.LOCKPICK}),
	TOP_FLOOR_OF_THE_YANILLE_WATCHTOWER(29057, true, new int[]{ItemID.DRAGON_PLATESKIRT, ItemID.DEATH_CLIMBINGBOOTS, ItemID.DRAGON_CHAINBODY, ItemID.BULLROARER}), // Gold trim variants
	DEATH_ALTAR(29058, true, new int[]{ItemID.RING_OF_WEALTH, ItemID.TIARA_DEATH, ItemID.CAPE_OF_LEGENDS}), // Ring of wealth charges
	BEHIND_MISS_SCHISM_IN_DRAYNOR_VILLAGE(29059, true, new int[]{ItemID.ABYSSAL_WHIP, ItemID.CAPE_OF_LEGENDS, ItemID.DAGGANOTH_RANGED_LEGS}), // Whip variants (Ice, Lava, Tentacle)
	NORTHWESTERN_CORNER_OF_THE_ENCHANTED_VALLEY(29060, true, new int[]{ItemID.DRAGON_AXE}), // Axe variants (Dragon, Crystal, Infernal)
	NORTH_OF_MOUNT_KARUULM(34647, false, new int[]{ItemID.ADAMNT_WARHAMMER, ItemID.RING_OF_LIFE, ItemID.MITHRIL_ARMOURED_BOOTS}),
	GYPSY_TENT_ENTRANCE(34736, false, new int[]{ItemID.GOLD_RING, ItemID.GOLD_NECKLACE}),
	FINE_CLOTHES_ENTRANCE(34737, false, new int[]{ItemID.CHEFS_HAT, ItemID.RED_CAPE}),
	BOB_AXES_ENTRANCE(34738, false, new int[]{ItemID.BRONZE_AXE, ItemID.LEATHER_BOOTS}),
	CRYSTALLINE_MAPLE_TREES(34953, true, new int[]{ItemID.NATURE_STAFF_UNCHARGED, ItemID.TIARA_NATURE}), // Bryophyta's staff (Charged/Uncharged)
	CHARCOAL_BURNERS(41758, true, new int[]{ItemID.TITHE_REWARD_HAT_MALE, ItemID.SHAYZIEN_BODY_5, ItemID.PYROMANCER_BOTTOM}), // Farmer's hat (Male/Female)
	FORTIS_GRAND_MUSEUM(50738, false, new int[]{ItemID.EMERALD_NECKLACE, ItemID.BLUE_SKIRT, ItemID.GNOME_ROBETOP_TURQUOISE}),
	TEMPLE_SOUTHEAST_OF_THE_BAZAAR(50739, true, new int[]{ItemID.SUNFIRE_HELM}), // Any Sunfire Fanatic piece
	CAM_TORUM_ENTRANCE(50740, true, new int[]{ItemID.FROST_MOON_HELM, ItemID.FROST_MOON_CHESTPLATE, ItemID.FROST_MOON_TASSETS, ItemID.FROSTMOON_SPEAR}), // Degraded Blue Moon variants
	WESTERN_SALVAGER_OVERLOOK(54275, false, new int[]{ItemID.HUEY_COIF, ItemID.HUEY_VAMBRACES}),
	TWILIGHT_TEMPLE_MINE(55403, false, new int[]{ItemID.MAPLE_LONGBOW, ItemID.STRUNG_RUBY_AMULET, ItemID.STEEL_PLATELEGS}),
	ORTUS_MEETS_PROUDSPIRE(55404, false, new int[]{ItemID.BLUEWIZHAT, ItemID.WIZARDS_ROBE}),
	OUTSIDE_TWILIGHT_TEMPLE(55405, false, new int[]{ItemID.RUNE_LONGSWORD, ItemID.RUNE_PLATEBODY, ItemID.RUNE_PLATESKIRT}),
	PANDEMONIUM_BAR(58130, false, new int[]{ItemID.EYE_PATCH, ItemID.BRONZE_SCIMITAR}),
	WINTUMBER_ISLAND(58131, false, new int[]{ItemID.HUNDRED_PIRATE_CRAB_SHELL_HELM, ItemID.HUNDRED_PIRATE_CRAB_SHELL_GAUNTLET}),
	BRITTLE_ISLE(58132, false, new int[]{ItemID.MEDALLION_OF_THE_DEEP, ItemID.ROSEWOOD_BLOWPIPE});

	private final int objectId;
	private final boolean isFlexibleItemSet;
	private final int[] fallbackItemIds;

	StashUnitData(int objectId, boolean isFlexibleItemSet, int[] fallbackItemIds)
	{
		this.objectId = objectId;
		this.isFlexibleItemSet = isFlexibleItemSet;
		this.fallbackItemIds = fallbackItemIds;
	}

	private static final Map<Integer, StashUnitData> lookupMap = new HashMap<>();

	static
	{
		for (StashUnitData unit : values())
		{
			lookupMap.put(unit.getObjectId(), unit);
		}
	}

	/**
	 * Retrieves the STASH unit data based on the physical game Object ID.
	 */
	public static StashUnitData getByObjectId(int objectId)
	{
		return lookupMap.get(objectId);
	}
}